export const SIGNUP_START = 'SIGNUP_START';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAIL = 'SIGNUP_FAIL';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_START = 'LOGOUT_START';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const QUES_START = 'QUES_START';
export const QUES_SUCCESS = 'QUES_SUCCESS';
export const QUES_FAIL = 'QUES_FAIL';

export const ADD_QUES_START = 'ADD_QUES_START';
export const ADD_QUES_SUCCESS = 'ADD_QUES_SUCCESS';
export const ADD_QUES_FAIL = 'ADD_QUES_FAIL';

export const COURSE_START = 'COURSE_START';
export const COURSE_SUCCESS = 'COURSE_SUCCESS';
export const COURSE_FAIL = 'COURSE_FAIL';

export const ADD_COURSE_START = 'ADD_COURSE_START';
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS';
export const ADD_COURSE_FAIL = 'ADD_COURSE_FAIL';

export const ADD_COURSE_CONTENT_START = 'ADD_COURSE_CONTENT_START';
export const ADD_COURSE_CONTENT_SUCCESS = 'ADD_COURSE_CONTENT_SUCCESS';
export const ADD_COURSE_CONTENT_FAIL = 'ADD_COURSE_CONTENT_FAIL';

export const UPDATE_COURSE_START = 'UPDATE_COURSE_START';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const UPDATE_COURSE_FAIL = 'UPDATE_COURSE_FAIL';

export const UPDATE_COURSE_CONTENT_START = 'UPDATE_COURSE_CONTENT_START';
export const UPDATE_COURSE_CONTENT_SUCCESS = 'UPDATE_COURSE_CONTENT_SUCCESS';
export const UPDATE_COURSE_CONTENT_FAIL = 'UPDATE_COURSE_CONTENT_FAIL';

export const DELETE_COURSE_CONTENT_START = 'DELETE_COURSE_CONTENT_START';
export const DELETE_COURSE_CONTENT_SUCCESS = 'DELETE_COURSE_CONTENT_SUCCESS';
export const DELETE_COURSE_CONTENT_FAIL = 'DELETE_COURSE_CONTENT_FAIL';

export const DELETE_COURSE_START = 'DELETE_COURSE_START';
export const DELETE_COURSE_SUCCESS = 'DELETE_COURSE_SUCCESS';
export const DELETE_COURSE_FAIL = 'DELETE_COURSE_FAIL';